#ifndef _EVENTSELECTION_HH_
#define _EVENTSELECTION_HH_

#include "CAnalysisModule.hh"
#include "REventWmcHeader.hh"
#include "REventHeader.hh"
#include "WTrackBank.hh"
#include "WVertexBank.hh"
#include "WHitBank.hh"
#include "WClusterBank.hh"
#include "WHitScint.hh"
#include "CCardWDET.hh"
#include <TH1F.h>
#include <TH2F.h>
#include <TH1D.h>
#include <WClusterFinder.hh>
#include <FDETClusters.hh>
#include <FDFTHTracks.hh>
#include "CDTracksSimple.hh"
#include "SECGeo.hh"
#include "SECCluster.hh"
#include "FDEdep2Ekin.hh"
#include <fstream>
#include "TCutG.h"

class eventselection : public CAnalysisModule {

public:
    eventselection();
    explicit eventselection(const char * name);
    virtual ~eventselection();

    virtual void    ProcessEvent();
    virtual void    Clear(Option_t *option = "");
    virtual void    Print(Option_t *option = "");
    virtual void    UserCommand(CCommand * command);

private:
    REventWmcHeader *fEventHeader;      //WMC Event header (contains event weight)
    REventHeader    *fHeader;           //DATA Event Header

    WTrackBank      *fFDTrackBank;      //FD Trackbank
    WTrackBank      *fCDTrackBank;      //CD Trackbank

    WTrackBank      *fMCTrackBank;      //MC Track bank (contains true MC tracks (from event generator)

    FDFTHTracks     *fFDTrackFinder;    //FD Trackfinder
    CDTracksSimple  *fCDTrackFinder;    //CD Trackfinder

    //MCTrackFinder   *fMCTrackFinder;

    //MC vertex bank. Each MC event should have one vertex,
    //which contains all emitted particles as generated by event generator
    WVertexBank     *fMCVertexBank;

    //Used to extract detector plane numbers, which are used eg in FD tracks
    CCardWDET       *fDetectorTable;

    SECGeo          *fGeometry;
    SECCluster      *fEMinCluster;

    //FDEdep2Ekin   *fFDEdep2Ekin;      //change Edep to Ekin (WasaParameters)

    //track type, particle type and FD planes new definition
    enum TrackTypes{kFDN=1,kFDC=2,kCDN=11,kCDC=12};  //FD neutral, FD charged, CD neutral, CD charged

    enum ParticleTypes{
            kDummy=0,kGamma=1,kPositron=2,kElectron=3,kPi0=7,kPiPlus=8,kPiMinus=9,
            kNeutron=13,kProton=14,kEta=17,kDeuteron=45,kTriton=46,kHe3=49,
            kDDummy=50
    };

    enum ForwardDetectorPlanes{
            kFWC1=10,kFWC2=11,kFTH1=1,kFTH2=2,kFTH3=3,
            kFRH1=4,kFRH2=5,kFRH3=6,kFRH4=7,kFRH5=8,kFVH=9
    };

    //WASA plane number for first(last) plane of these detectors
    //(take into acconunt at the beginning of the analysis program)
    Int_t   kFTH1_old, kFRH1_old, kFVH1_old, kFWC1_old, kPSfirst_old, kPSlast_old, kSEfirst_old, kSElast_old;

protected:
    void    SetupSpectra(const char * path);

    FILE *BMfile;
    TGraph *gBeamMomentum;

    TCutG *cutg0,*cutg1,*cutg2,*cutg3,*cutg4;

    //Statistics after cuts
    TH1F    *hStatistics[5];

    //Monte Carlo (generator)
    TH1F    *hGenerated_Q,*hAccepted_Q,*hp_beam_MC;

    TH1F    *hEkin_p_lab_MC,*hp_p_lab_MC,*hE_p_lab_MC,*hTheta_p_lab_MC,*hPhi_p_lab_MC;
    TH1F    *hEkin_d_lab_MC,*hp_d_lab_MC,*hE_d_lab_MC,*hTheta_d_lab_MC,*hPhi_d_lab_MC;
    TH1F    *hEkin_g1_lab_MC,*hp_g1_lab_MC,*hE_g1_lab_MC,*hTheta_g1_lab_MC,*hPhi_g1_lab_MC;
    TH1F    *hEkin_g2_lab_MC,*hp_g2_lab_MC,*hE_g2_lab_MC,*hTheta_g2_lab_MC,*hPhi_g2_lab_MC;
    TH1F    *hEkin_pi0_lab_MC,*hp_pi0_lab_MC,*hE_pi0_lab_MC,*hTheta_pi0_lab_MC,*hPhi_pi0_lab_MC;

    TH2F    *hEkin_vs_Theta_p_lab_MC,*hEkin_vs_Theta_d_lab_MC,*hEkin_vs_Theta_pi0_lab_MC;
    TH2F    *hEkin_vs_Theta_g1_lab_MC,*hEkin_vs_Theta_g2_lab_MC,*hEkin_vs_Theta_gammas_lab_MC;
    TH2F    *hEkin_vs_Theta_p_lab_acc_MC,*hEkin_vs_Theta_d_lab_acc_MC;
    TH2F    *hEkin_vs_Theta_gammas_lab_acc_MC,*hEkin_vs_Theta_g1_lab_acc_MC,*hEkin_vs_Theta_g2_lab_acc_MC;

    TH2F    *hEkin_vs_Theta_p_cm_MC,*hEkin_vs_Theta_d_cm_MC,*hEkin_vs_Theta_pi0_cm_MC;
    TH2F    *hEkin_vs_Theta_g1_cm_MC,*hEkin_vs_Theta_g2_cm_MC;

    TH1F    *hEkin_p_cm_MC,*hp_p_cm_MC,*hE_p_cm_MC,*hTheta_p_cm_MC,*hPhi_p_cm_MC;
    TH1F    *hEkin_d_cm_MC,*hp_d_cm_MC,*hE_d_cm_MC,*hTheta_d_cm_MC,*hPhi_d_cm_MC;
    TH1F    *hEkin_g1_cm_MC,*hp_g1_cm_MC,*hE_g1_cm_MC,*hTheta_g1_cm_MC,*hPhi_g1_cm_MC;
    TH1F    *hEkin_g2_cm_MC,*hp_g2_cm_MC,*hE_g2_cm_MC,*hTheta_g2_cm_MC,*hPhi_g2_cm_MC;
    TH1F    *hEkin_pi0_cm_MC,*hp_pi0_cm_MC,*hE_pi0_cm_MC,*hTheta_pi0_cm_MC,*hPhi_pi0_cm_MC;

    TH1F    *hOpeningAngle_g1_g2_lab_MC,*hOpeningAngle_g1_g2_cm_MC;
    TH1F    *hOpeningAngle_pi0_p_lab_MC,*hOpeningAngle_pi0_p_cm_MC;

    TH2F    *hTheta_g1_vs_Theta_g2_lab_MC,*hTheta_g1_vs_Theta_g2_cm_MC;
    TH2F    *hTheta_p_vs_Theta_d_lab_MC,*hTheta_p_vs_Theta_d_lab_cut_MC,*hTheta_p_vs_Theta_d_cm_MC;

    TH1F    *hIM_pion_MC;
    TH1F    *hMM_nucleon_MC,*hMM_deuteron_MC,*hMM_proton_MC;
    TH1F    *hME_nucleon_MC,*hME_deuteron_MC,*hME_proton_MC;
    TH2F    *hMMvsME_nucleon_MC;

    //Reconstructed
    TH1F    *hQ[6][10][10][10],*hp_beam[2][1];

    TH1F    *hNeutralTracksCD[2][1],*hChargedTracksCD[2][1],*hChargedTracksFD[2][1];

    TH1F    *hTime_FDC[5][8],*hTheta_FDC[5][8],*hPhi_FDC[5][8];
    TH1F    *hTime_CDC[5][8],*hTheta_CDC[5][8],*hPhi_CDC[5][8],*hMom_CDC[5][8];
    TH1F    *hTime_CDN[5][8],*hTheta_CDN[5][8],*hPhi_CDN[5][8],*hMom_CDN[5][8];

    TH2F    *hEdepFWC1vsFRH1[5][8],*hEdepFWC2vsFRH1[5][8],*hEdepFWC1vsFRH1FRH2FRH3[5][8];
    TH2F    *hEdepFTH1vsFRH1[5][8],*hEdepFRH1vsFRH2[5][8],*hEdepFRH2vsFRH3[5][8];

    TH2F    *hEdepPSBvsSEC[5][8],*hEdepPSBvsSigMom[5][8],*hEdepSECvsSigMom[5][8];

    TH1F    *hp_g1_lab[5][8],*hp_g1_cm[5][8];
    TH1F    *hTheta_g1_lab[5][8],*hTheta_g1_cm[5][8];
    TH1F    *hPhi_g1_lab[5][8],*hPhi_g1_cm[5][8];
    TH2F    *hEkin_vs_Theta_g1_lab[5][8],*hEkin_vs_Theta_g1_cm[5][8];

    TH1F    *hp_g2_lab[5][8],*hp_g2_cm[5][8];
    TH1F    *hTheta_g2_lab[5][8],*hTheta_g2_cm[5][8];
    TH1F    *hPhi_g2_lab[5][8],*hPhi_g2_cm[5][8];
    TH2F    *hEkin_vs_Theta_g2_lab[5][8],*hEkin_vs_Theta_g2_cm[5][8];

    TH1F    *hOpeningAngle_g1_g2_lab[5][8],*hOpeningAngle_g1_g2_cm[5][8];

    TH2F    *hTheta_g1_vs_Theta_g2_lab[5][8],*hTheta_g1_vs_Theta_g2_cm[5][8];

    TH1F    *hp_pi0_lab[5][8],*hp_pi0_cm[5][8];
    TH1F    *hE_pi0_lab[5][8],*hE_pi0_cm[5][8];
    TH1F    *hEkin_pi0_lab[5][8],*hEkin_pi0_cm[5][8];
    TH1F    *hTheta_pi0_lab[5][8],*hTheta_pi0_cm[5][8];
    TH1F    *hPhi_pi0_lab[5][8],*hPhi_pi0_cm[5][8];
    TH2F    *hEkin_vs_Theta_pi0_lab[5][8],*hEkin_vs_Theta_pi0_cm[5][8];

    TH1F    *hp_p_lab[5][8],*hp_p_cm[5][8];
    TH1F    *hE_p_lab[5][8],*hE_p_cm[5][8];
    TH1F    *hEkin_p_lab[5][8],*hEkin_p_cm[5][8];
    TH1F    *hTheta_p_lab[5][8],*hTheta_p_cm[5][8];
    TH1F    *hPhi_p_lab[5][8],*hPhi_p_cm[5][8];
    TH2F    *hEkin_vs_Theta_p_lab[5][8],*hEkin_vs_Theta_p_cm[5][8];

    TH1F    *hp_d_lab[5][8],*hp_d_cm[5][8];
    TH1F    *hE_d_lab[5][8],*hE_d_cm[5][8];
    TH1F    *hEkin_d_lab[5][8],*hEkin_d_cm[5][8];
    TH1F    *hTheta_d_lab[5][8],*hTheta_d_cm[5][8];
    TH1F    *hPhi_d_lab[5][8],*hPhi_d_cm[5][8];
    TH2F    *hEkin_vs_Theta_d_lab[5][8],*hEkin_vs_Theta_d_cm[5][8];

    TH2F    *hTheta_p_vs_Theta_d_lab[5][8],*hTheta_p_vs_Theta_d_cm[5][8];

    TH1F    *hOpeningAngle_pi0_p_lab[5][8],*hOpeningAngle_pi0_p_cm[5][8];

    TH1F    *hIM_pion[5][8],*hMM_nucleon[5][8],*hME_nucleon[5][8];
    TH2F    *hMMvsME_nucleon[5][8],*hIMvsMM[5][8];

    TH1F    *hEnergy_additional_gammas,*hEnergy_additional_gammas_cut;

    ClassDef(eventselection,0);

};

#endif
